export const WIDGET_TYPES = [
  {
    type: 'kpi',
    label: 'KPI Card',
    icon: 'TrendingUp',
    description: 'Single metric with trend',
    defaultConfig: {
      title: 'KPI Card',
      metric: 'totalRevenue',
      w: 2,
      h: 2,
      aggregation: 'Sum',
      format: 'Number',
      precision: 0,
    },
  },
  {
    type: 'bar',
    label: 'Bar Chart',
    icon: 'BarChart2',
    description: 'Compare across categories',
    defaultConfig: {
      title: 'Bar Chart',
      xAxis: 'product',
      yAxis: 'total_amount',
      w: 5,
      h: 5,
    },
  },
  {
    type: 'line',
    label: 'Line Chart',
    icon: 'TrendingUp',
    description: 'Trends over time',
    defaultConfig: {
      title: 'Line Chart',
      xAxis: 'order_date',
      yAxis: 'total_amount',
      groupBy: 'day',
      w: 5,
      h: 5,
    },
  },
  {
    type: 'area',
    label: 'Area Chart',
    icon: 'Activity',
    description: 'Cumulative trends',
    defaultConfig: {
      title: 'Area Chart',
      xAxis: 'order_date',
      yAxis: 'total_amount',
      groupBy: 'week',
      w: 5,
      h: 5,
    },
  },
  {
    type: 'scatter',
    label: 'Scatter Plot',
    icon: 'Circle',
    description: 'Quantity vs price correlation',
    defaultConfig: {
      title: 'Scatter Plot',
      w: 5,
      h: 5,
    },
  },
  {
    type: 'pie',
    label: 'Pie Chart',
    icon: 'PieChart',
    description: 'Distribution breakdown',
    defaultConfig: {
      title: 'Pie Chart',
      groupBy: 'status',
      w: 4,
      h: 4,
    },
  },
  {
    type: 'table',
    label: 'Data Table',
    icon: 'Table',
    description: 'Top orders ranked',
    defaultConfig: {
      title: 'Top Orders',
      sortBy: 'total_amount',
      rows: 5,
      w: 4,
      h: 4,
    },
  },
];
